apiVersion: apps/v1
kind: Deployment
metadata:
    name: sample-rest-deploy
spec:
    replicas: 2
    selector:
       matchLabels:
          app: app-rest
    template:
       metadata:
          labels:
             app: app-rest
       spec:
          containers:
          - name: sample-rest
            image: docker.pkg.github.com/nemocapt/otus_dock/sample-rest:v5
            ports:
              - name: rest 
                containerPort: 8000
            env:
              - name: URI
                valueFrom:
                  secretKeyRef:
                    name: mongo-secret
                    key: URI